name: Android Tests

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew test

    - name: Run UI tests
      run: ./gradlew connectedAndroidTest

    - name: Run screenshot tests
      run: ./gradlew validateDebugScreenshotTest

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          app/build/reports/tests
          app/build/reports/androidTests
          app/screenshots 
